// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwD6bNcYu6tM3cT6qkGvQw3H710eSahzA',
    appId: '1:315246059123:web:400df9f93c88b9b2529406',
    messagingSenderId: '315246059123',
    projectId: 'cseclubhub-25c92',
    authDomain: 'cseclubhub-25c92.firebaseapp.com',
    storageBucket: 'cseclubhub-25c92.firebasestorage.app',
    measurementId: 'G-8G9NFB0LG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAveN0fOS-7XB5y-nyy2DJY3Dz2XxUGjCs',
    appId: '1:315246059123:android:0745da927b872cac529406',
    messagingSenderId: '315246059123',
    projectId: 'cseclubhub-25c92',
    storageBucket: 'cseclubhub-25c92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbetNDIY-HAfPwNjfftbmP6JuLt4F8H4M',
    appId: '1:315246059123:ios:bd49fc696997739c529406',
    messagingSenderId: '315246059123',
    projectId: 'cseclubhub-25c92',
    storageBucket: 'cseclubhub-25c92.firebasestorage.app',
    iosBundleId: 'com.example.cseclubhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbetNDIY-HAfPwNjfftbmP6JuLt4F8H4M',
    appId: '1:315246059123:ios:bd49fc696997739c529406',
    messagingSenderId: '315246059123',
    projectId: 'cseclubhub-25c92',
    storageBucket: 'cseclubhub-25c92.firebasestorage.app',
    iosBundleId: 'com.example.cseclubhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwD6bNcYu6tM3cT6qkGvQw3H710eSahzA',
    appId: '1:315246059123:web:9d9b10ea122934f0529406',
    messagingSenderId: '315246059123',
    projectId: 'cseclubhub-25c92',
    authDomain: 'cseclubhub-25c92.firebaseapp.com',
    storageBucket: 'cseclubhub-25c92.firebasestorage.app',
    measurementId: 'G-WQJWP9LKQ0',
  );
}
